### ISSUE TITLE
Zoom-independent shape outlines/vertices

### ISSUE THREAD

**Issue by clint-tseng** [xyonix/vannot#31] opened 2018-07-04 22:35 UTC
From #25:
> when trying to draw the very detailed edges of some objects I noticed it was a bit hard to get accurate point positioning and that the points/line elements don't seem to scale with zooming.

> E.g. if you zoom in fully it seems like the points don't scale down at all to account for being zoomed in and if the object is detailed/small it becomes difficult to also "see through" to where the points are actually placed: (contrived example)
> ![image](https://user-images.githubusercontent.com/2565985/42182496-397ef434-7df3-11e8-86ac-9382c903a2d6.png)

**Comment by clint-tseng** [comment] 2018-07-04 22:40
So, I've rigged up a branch that changes the behavior seen described in the ticket. It can be found [here](https://github.com/xyonix/vannot/tree/cxlt/figure-scaling). The main issue with it is that it's far more performance-intensive during zoom and pan operations; the old methodology didn't actually change the SVG at all, it just changed the viewport into the extant SVG structure so it was all processed natively. In order to make the weights appear to not change, we have to recompute and redraw all the elements with different strokes with every zoom change.

This isn't a problem on my laptop, but I want to be sure it's workable on the expected target machines before committing to this change. And if we do, I'll try to put a little more into granular optimization than I did in the experimental branch thus far.

(ping @chasemaier)

**Comment by alex9311** [comment] 2018-07-20 20:20
I checked out the branch and ran locally. Performance seems fine. Our annotators have nice macs so I'm not concerned. 

The dots are better in the branch, but still running into problems. For example, if you have a corner with rounded edges coming into it you get a lot of dots. Talking with Chase, we propose the solution of hiding the "intermediate" dots that show up when the shape is focused. I've never used them to modify a shape after I've drawn it. Maybe a hotkey to show them? "Hold ctrl to modify existing edges with a new vertice"

does that make sense?

![more-dots](https://user-images.githubusercontent.com/1326899/43023405-9c0a46aa-8c1f-11e8-9510-50b3567d61ea.png)

**Comment by clint-tseng** [comment] 2018-07-25 23:48
Yeah, I definitely see what you mean. Perhaps I'll have them not show below some minimum distance between true vertices.

**Comment by alex9311** [comment] 2018-07-25 23:55
that should work as well, whatever is easiest for you

**Comment by clint-tseng** [comment] 2018-08-02 17:54
Okay, I've pushed a commit to the figure-scaling branch that does two things:

* Never shows implicit points if the anchor points are within 40 screenspace px of each other (so if you zoom in and they grow further apart they'll pop back up.
* Use screenspace px rather than canvas px to determine whether to show an implicit point when the mouse approaches, so it doesn't overaccount when zoomed in.

Let me know what you think!

**Comment by chasemaier** [comment] 2018-08-07 00:16
Some additional usability observations:

* The "active" main drawing point/line does not scale with zoom. Makes it hard to select points accurately.
![image](https://user-images.githubusercontent.com/2565985/43746043-c8fd335a-9996-11e8-97bd-f1a29841ee97.png)
* It is hard to select the correct point since the main selection point is so large + opaque. Maybe we can make the point under cursor be semi-transparent? An opacity of ~0.4 or less looked good to me for the point/segment following the mouse.
* This is actually somewhat true for the points/lines when resizing an existing polygon too. It's tough to position the points accurately without being able to see through.
* I've run into a couple times where i'm aligning points on the border of two polygons and i end up grabbing the "higher z-index" one (which is not "selected" at the time) when i'm aiming for a point that is halfway underneath it from the "selected" polygon. Would be nice if there was some way to prevent this.
![image](https://user-images.githubusercontent.com/2565985/43746307-6f84adce-9998-11e8-843d-205fe8a4136a.png)
* Is the scroll increment easy to customize? For me, the scroll increment is too small and it feel like i have to scroll for 30 seconds to get all the way zoomed in.
* It doesn't seem uncommon for the existing polygons instance grouping lines to "get in the way" of the new stuff you might want to draw. Once you get about 3 instances groups in a frame they start to be hard to tell apart and can overlap pretty severely because of the acute angles. Same as above, with these in the way getting finely positioned points is pretty tough. The size of these lines also don't decrease as you zoom in.
![image](https://user-images.githubusercontent.com/2565985/43746755-03f3d0be-999b-11e8-9df8-79e8dcb6a399.png)

The mid-points do seem to work better in this branch, though there are still times when they overlap (e.g. many angles near each other so it overlaps the N+1th point or further away than the direct neighbor). I wouldn't be opposed to a hotkey to toggle those points on/off entirely as I haven't found I reach for them often.

**Comment by clint-tseng** [comment] 2018-08-07 16:28
* Making some points less opaque: sounds good, I think—I'm not completely sure I understand exactly the ones you're referring to but I'll give it a shot.
* Main selection point not scaling: ugh, okay. I might completely redo our approach to scaling yet again if this branch is the direction we are going in.
* Z-indexing issues: will resolve.
* Scroll increment: I'll do my best. There is already a _lot_ of code in there that attempts to normalize the incredibly wild differences between platforms (delta numbers from eg mac reach the thousands, while windows will never output more than 40... unless someone has tinkered with the registry). So your annotators on Macs right now will actually have pretty smooth experiences at the moment. I'll take another look at that normalization.
* Instance Grouping Lines: would it help if they dimmed a bit while you were drawing? As for the line size, that's the same issue as the wip-drawing segment/dot, I think I have to completely rewrite the scaling code again to make that work better.
* Midpoints: I'd still prefer to avoid a hotkey, so if you can send me screenshots of some of these degenerate cases I can write logic to improve them.

**Comment by chasemaier** [comment] 2018-08-09 00:27
> Instance Grouping Lines: would it help if they dimmed a bit while you were drawing?

Yes, I think that makes sense. If you're actively drawing, almost everything else could get very dim/transparent or go away until that particular polygon is complete, I think.

> Midpoints: I'd still prefer to avoid a hotkey, so if you can send me screenshots of some of these degenerate cases I can write logic to improve them.

Probably lower priority, but here's a contrived example -- just can get a bit crowded:

![image](https://user-images.githubusercontent.com/2565985/43870958-19ffd62e-9b2f-11e8-860f-d6a10efb2c75.png)

**Comment by clint-tseng** [comment] 2018-08-10 03:49
Okay, I just pushed an update that should address almost all of the above:
* Making some graphics less opaque when working on stuff: is done.
* Instance Grouping Lines: included in the above (done).
* WIP drawing segments not scaling: is fixed.
* Z-indexing issues: are fixed.
* Midpoints: are now much, much less talkative. you can read the commit message if you want the details, but I bet they'll be fine now.

* Scroll increment: is the one thing I haven't touched yet, since if your users are all on macs at least they should be fine, and I'll get around to this soon.

**Comment by chasemaier** [comment] 2018-08-13 17:19
Thanks. I think those mostly look good to me.

The one thing that seems like a regression/new bug is the drag-to-select rectangle. The drag to select functionality seems to work as expected but the visible blue rectangle to show the selected area does not map to the expected coordinates on the canvas.

The underlying points that get activated are all in the correct canvas area, it's just the visual rectangle that doesn't seem to be scaled properly to cover the expected area.

**Comment by clint-tseng** [comment] 2018-08-14 07:36
Figured I would end up missing a case. That's covered now, and I cleaned up a few other visual things, and was happy enough with the result to merge to master. I think that concludes this ticket, if nothing else is broken.

**Comment by chasemaier** [comment] 2018-08-14 21:04
Agreed. Feel free to close this. There is one other item I ran across, but I think it is unrelated. I'll open a separate issue.

**Closed** 2018-08-22 23:03 UTC
