### ISSUE TITLE
Zooming Moves Points Relative To Image

### ISSUE THREAD

**Issue by chasemaier** [xyonix/vannot#16] opened 2018-05-09 23:40 UTC
Drawing a polygon and scrolling / zooming causes points to no longer be positioned in the expected location relative to the underlying image.

Using the actual browser zoom feature causes even more de-sync between the two than the in-app zoom feature itself.

**Comment by clint-tseng** [comment] 2018-05-10 00:25
This is likely a duplicate of #15, as the `viewBox` attribute is what aligns the points and the video. I will take a look tomorrow.

**Closed** 2018-05-10 23:32 UTC
