### ISSUE TITLE
selected shape "Part of..." dropdown values hidden

### ISSUE THREAD

**Issue by alex9311** [xyonix/vannot#6] opened 2018-04-30 20:44 UTC
when I expand the drop down to label the selected shape, only the currently selected label is readable. Hovering over the other options reveals the text. Seems like a css issue

**Comment by clint-tseng** [comment] 2018-04-30 20:58
Thanks for the report! May I ask what your platform/browser are?

**Comment by alex9311** [comment] 2018-04-30 21:07
Of course! I'm on ubuntu 16.04 running Chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by clint-tseng** [comment] 2018-05-02 23:29
I'll have to install Ubuntu to try to reproduce this; I can't get it to happen on macOS. It'll have to wait a little bit until I can do this on a machine. It's certainly a browser bug, but I have to see it to figure out how to avoid it.

**Comment by chasemaier** [comment] 2018-05-03 22:04
This seems to be an issue with the use of `background: transparent` on various `selects`s, which Chrome does not support.

**Comment by clint-tseng** [comment] 2018-05-03 22:07
A sensible explanation, though it _does_ work on Chrome on my Mac. I was hoping not to have to manually set the color as that affects the dropdown popup. I'll give a few things a try.

**Comment by chasemaier** [comment] 2018-05-11 22:14
@clint-tseng FYI, This fixed that particular "part-of" dropdown, but all other selects on the page (e.g. top-right) still have the transparent background.

I'd also suggest adding margin between the label and select.

![image](https://user-images.githubusercontent.com/2565985/39949160-fad230b8-552d-11e8-8f44-1e4e3a59167b.png)

**Comment by clint-tseng** [comment] 2018-05-11 22:30
Great—good to hear. I'll apply that fix throughout, then, and standardize the padding. Thanks!

**Comment by chasemaier** [comment] 2018-05-25 22:37
The associated fix does not seem to resolve the issue as the "transparent" declaration still takes preference over the explicit color.

![image](https://user-images.githubusercontent.com/2565985/40568782-89750d32-6031-11e8-8e2c-b1cb19e17cd5.png)

**Comment by clint-tseng** [comment] 2018-05-25 23:04
:/ I was afraid of that.

> theoretically any browser that doesn't support the transparent background setting should then fall back on the #242424 rule and ignore the transparent rule. but i suspect chrome-linux /thinks/ it /does/ support the rule and might try to do it anyway, which would nullify this fix. in which case the best thing i can think of is to get rid of the transparency.

So I guess I'll do what past me suggested.

**Comment by chasemaier** [comment] 2018-05-25 23:26
Yeah, to be clear, the issue only currently exists for the dropdowns in the top-right. The other "part of" one in the bottom got fixed with the initial change.

**Comment by clint-tseng** [comment] 2018-05-26 00:41
Yeah—I tried to have my cake and eat it too. I'll just make the whole thing transparent or something.

**Closed** 2018-07-11 22:33 UTC
